/*
 * pvmpower - Gunyah protected-VM power driver (PSCI shutdown / reboot bridge).
 *
 * crosvm on this platform exposes no ACPI power or reset registers (the ACPI
 * tables are generated by edk2 from the FDT), so Windows' native S5 path has
 * nothing to poke and the VM hangs at the very end of shutdown until the host
 * kills it (DRIVER_POWER_STATE_FAILURE when power IRPs then time out). The
 * platform DOES implement PSCI via HVC: Linux/edk2 power off and reboot
 * through it, Gunyah forwards SYSTEM_OFF / SYSTEM_RESET to crosvm, crosvm
 * exits with a distinct code (reset = 32) and the DroidVM daemon relaunches
 * the VM on reset. This driver bridges Windows onto that path:
 *
 *  - It loads as a PnP UPPER FILTER on the rdmapool device (ACPI\RDMA0000,
 *    installed by rdmapool.inf), so it sits in the PnP tree, receives the
 *    system power IRPs sent to that stack, and needs no devnode creation -
 *    plain offline driver injection (DISM) is enough.
 *  - IRP_MJ_POWER preprocess (KMDF does not surface raw power IRPs): peek the
 *    S5 SET_POWER IRP (SystemState == PowerSystemShutdown) and cache its
 *    ShutdownType (POWER_ACTION) - the documented reboot-vs-poweroff
 *    discriminator. The IRP is passed back untouched via
 *    WdfDeviceWdmDispatchPreprocessedIrp.
 *  - IRP_MJ_SHUTDOWN preprocess + IoRegisterLastChanceShutdownNotification:
 *    at the very end of shutdown issue PSCI SYSTEM_RESET (0x84000009) when a
 *    reboot was requested (PowerActionShutdownReset), else SYSTEM_OFF
 *    (0x84000008).
 *
 * Platform gate is implicit: ACPI\RDMA0000 exists only on the Gunyah pVM
 * (edk2 generates it from the FDT restricted-DMA-pool node), so on QEMU/KVM
 * or any ACPI-complete platform this driver never loads and Windows' native
 * power paths run unmodified - the same disk image boots elsewhere.
 *
 * Copyright (c) 2026
 * SPDX-License-Identifier: BSD-2-Clause-Patent
 */

#include <ntddk.h>
#include <wdf.h>

/* PSCI function IDs (SMC64), conduit "hvc" on this platform. Stub in
 * pvmpower_psci.asm places fn/args in x0-x3 per the C ABI and executes HVC #0. */
extern unsigned long long PsciHvcCall(unsigned long long Fn,
                                      unsigned long long Arg1,
                                      unsigned long long Arg2,
                                      unsigned long long Arg3);
#define PSCI_SYSTEM_OFF   0x84000008ULL
#define PSCI_SYSTEM_RESET 0x84000009ULL

DRIVER_INITIALIZE DriverEntry;
EVT_WDF_DRIVER_DEVICE_ADD PvmPowerEvtDeviceAdd;
EVT_WDFDEVICE_WDM_IRP_PREPROCESS PvmPowerPowerIrpPreprocess;
EVT_WDFDEVICE_WDM_IRP_PREPROCESS PvmPowerShutdownIrp;

/* ShutdownType (POWER_ACTION) captured from the S5 system power IRP; read at
 * last-chance shutdown. PowerActionNone until an S5 IRP is seen -> defaults to
 * SYSTEM_OFF, which matches the pre-reboot-support behavior. */
static volatile LONG g_ShutdownAction = PowerActionNone;

/*
 * IRP_MJ_POWER preprocess: peek, never complete. Cache the ShutdownType from
 * the S5 SET_POWER IRP; hand every IRP straight back to the framework. May run
 * up to DISPATCH_LEVEL, so no probing here.
 */
NTSTATUS
PvmPowerPowerIrpPreprocess(_In_ WDFDEVICE Device, _Inout_ PIRP Irp)
{
    PIO_STACK_LOCATION irpStack = IoGetCurrentIrpStackLocation(Irp);

    if (irpStack->MinorFunction == IRP_MN_SET_POWER && irpStack->Parameters.Power.Type == SystemPowerState &&
        irpStack->Parameters.Power.State.SystemState == PowerSystemShutdown)
    {
        InterlockedExchange(&g_ShutdownAction, (LONG)irpStack->Parameters.Power.ShutdownType);
        DbgPrintEx(DPFLTR_DEFAULT_ID,
                   DPFLTR_INFO_LEVEL,
                   "pvmpower: S5 power IRP, ShutdownType=%d (%s)\n",
                   irpStack->Parameters.Power.ShutdownType,
                   irpStack->Parameters.Power.ShutdownType == PowerActionShutdownReset ? "reboot" : "power-off");
    }

    return WdfDeviceWdmDispatchPreprocessedIrp(Device, Irp);
}

/*
 * Last-chance shutdown handler (IRP_MJ_SHUTDOWN arrives here only because
 * PvmPowerEvtDeviceAdd registered for last-chance notification). Runs at
 * PASSIVE_LEVEL at the very end of shutdown, after file systems flushed.
 */
NTSTATUS
PvmPowerShutdownIrp(_In_ WDFDEVICE Device, _Inout_ PIRP Irp)
{
    POWER_ACTION action = (POWER_ACTION)InterlockedCompareExchange(&g_ShutdownAction, 0, 0);
    ULONGLONG fn = (action == PowerActionShutdownReset) ? PSCI_SYSTEM_RESET : PSCI_SYSTEM_OFF;

    UNREFERENCED_PARAMETER(Device);

    /* We only load as a filter on ACPI\RDMA0000, so being here == Gunyah pVM. */
    DbgPrintEx(DPFLTR_DEFAULT_ID,
               DPFLTR_INFO_LEVEL,
               "pvmpower: last-chance shutdown, action=%d -> PSCI %s\n",
               action,
               fn == PSCI_SYSTEM_RESET ? "SYSTEM_RESET" : "SYSTEM_OFF");
    (void)PsciHvcCall(fn, 0, 0, 0);
    /* Should not return (VM reset or powered off). Fall through defensively. */
    DbgPrintEx(DPFLTR_DEFAULT_ID, DPFLTR_ERROR_LEVEL, "pvmpower: PSCI call returned!\n");

    Irp->IoStatus.Status = STATUS_SUCCESS;
    Irp->IoStatus.Information = 0;
    IoCompleteRequest(Irp, IO_NO_INCREMENT);
    return STATUS_SUCCESS;
}

NTSTATUS
PvmPowerEvtDeviceAdd(_In_ WDFDRIVER Driver, _Inout_ PWDFDEVICE_INIT DeviceInit)
{
    NTSTATUS status;
    WDFDEVICE device;

    UNREFERENCED_PARAMETER(Driver);

    /* Upper device filter on the rdmapool FDO: pass through everything we do
     * not explicitly preprocess. */
    WdfFdoInitSetFilter(DeviceInit);

    /* KMDF surfaces neither raw power IRPs nor IRP_MJ_SHUTDOWN; take both as
     * WDM preprocess callbacks. The power callback is peek-and-pass-through. */
    status = WdfDeviceInitAssignWdmIrpPreprocessCallback(DeviceInit, PvmPowerPowerIrpPreprocess, IRP_MJ_POWER, NULL, 0);
    if (!NT_SUCCESS(status))
    {
        DbgPrintEx(DPFLTR_DEFAULT_ID,
                   DPFLTR_ERROR_LEVEL,
                   "pvmpower: assign IRP_MJ_POWER preprocess failed 0x%x\n",
                   status);
        return status;
    }

    status = WdfDeviceInitAssignWdmIrpPreprocessCallback(DeviceInit, PvmPowerShutdownIrp, IRP_MJ_SHUTDOWN, NULL, 0);
    if (!NT_SUCCESS(status))
    {
        DbgPrintEx(DPFLTR_DEFAULT_ID,
                   DPFLTR_ERROR_LEVEL,
                   "pvmpower: assign IRP_MJ_SHUTDOWN preprocess failed 0x%x\n",
                   status);
        return status;
    }

    status = WdfDeviceCreate(&DeviceInit, WDF_NO_OBJECT_ATTRIBUTES, &device);
    if (!NT_SUCCESS(status))
    {
        DbgPrintEx(DPFLTR_DEFAULT_ID, DPFLTR_ERROR_LEVEL, "pvmpower: WdfDeviceCreate failed 0x%x\n", status);
        return status;
    }

    /* Fire PvmPowerShutdownIrp at the very end of system shutdown. */
    status = IoRegisterLastChanceShutdownNotification(WdfDeviceWdmGetDeviceObject(device));
    if (!NT_SUCCESS(status))
    {
        DbgPrintEx(DPFLTR_DEFAULT_ID,
                   DPFLTR_ERROR_LEVEL,
                   "pvmpower: IoRegisterLastChanceShutdownNotification failed 0x%x\n",
                   status);
        return status;
    }

    DbgPrintEx(DPFLTR_DEFAULT_ID, DPFLTR_INFO_LEVEL, "pvmpower: loaded (filter on the rdmapool stack)\n");
    return STATUS_SUCCESS;
}

NTSTATUS
DriverEntry(_In_ PDRIVER_OBJECT DriverObject, _In_ PUNICODE_STRING RegistryPath)
{
    WDF_DRIVER_CONFIG config;

    WDF_DRIVER_CONFIG_INIT(&config, PvmPowerEvtDeviceAdd);
    return WdfDriverCreate(DriverObject, RegistryPath, WDF_NO_OBJECT_ATTRIBUTES, &config, WDF_NO_HANDLE);
}
